variable "resource_group_location" {}
variable "resource_group_name" {}
variable "maria_db_server_capacity" {}
variable "maria_db_storage_mb" {}
variable "mariadb_admin_login_username" {}
variable "mariadb_admin_login_password" {}
variable "mariadb_ssl_enforcement" {}
variable "mariadb_name" {}
variable "env" {}
variable "domain" {}