variable "location" {}
variable "resource_group_name" {}
variable "env" {}
variable "subnet_id" {}
variable "subnet_id_appgateway" {}
variable "ssh_key_data" {}
variable "hostname" {}
variable "admin_username" {}
variable "image_name" {}
variable "azure_public_ip" {}
variable "resource_group_location" {}
variable "vm_increase_threshold" {}
variable "vm_decrease_threshold" {}
variable "az_virtual_network_name" {}
variable "cert_path" {}
variable "cert_password" {}