variable "location" {}
variable "resource_group_name" {}
variable "env" {}
variable "subnet_id" {}
variable "ssh_key_data" {}
variable "hostname" {}
variable "admin_username" {}
variable "image_name" {}
variable "azure_public_ip" {}