variable "aws_region" {}
variable "subnet1_az" {}
variable "subnet1_name" {}
variable "subnet1_cidr" {}
variable "subnet2_az" {}
variable "subnet2_cidr" {}
variable "subnet2_name" {}
variable "subnet3_cidr" {}
variable "subnet3_az" {}
variable "subnet3_name" {}
variable "vpc_cidr" {}
variable "vpc_name" {}
